# Project settings - General
version: 0.0.1
title: "Transit Vote 2015 - The Tyee"
subtitle: "Transit Vote 2015"
description: "The Transit Question: How Leaders Will Vote"
date: "March 9, 2015"
baseurl: ""
url: "http://transit-vote.thetyee.ca"

# Project settings - Analytics
analytics:
    ga_tracking_id: 'UA-169022-1'

# Project settings - Meta
author: "The Tyee"
robots: "index, follow"
revisit: "1 day"
copyright: "&copy; The Tyee 2015"
authors: "Tyee Staff"
updated: "March 9th, 2015"

# Project settings - URLs
urls:
    display: 'transit-vote.thetyee.ca'
    privacy: 'http://subscribe.thetyee.ca/privacy/'
    credits: '/credits'
    github: 'https://github.com/TheTyee/transit-vote.thetyee.ca'

# Project settings - Social
social:
    facebook:
        fb_admins:
            - 12345
        og_image: 'http://transit-vote.thetyee.ca/ui/img/transit-vote-share.png'
        og_sitename:
    twitter:
    gplus:

# Jekyll build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - bower.json
  - package.json
  - node_modules
  - bower_components
  - Gruntfile.js
  - gemfile
  - Gemfile
  - Gemfile.lock
  - _vendor
  - _fullsize
  - _thumbs
  - _data
# jekyll-assets pipeline - currently using this
assets:
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  dirname: assets
  # Base URL of assets paths.
  baseurl: /assets/
  sources:
    - ui/js/
    - ui/img/
    - ui/less/
    - ui/templates/
    - bower_components/jquery/dist/ 
    - bower_components/modernizr/
    - bower_components/bootstrap/dist/js/
    - bower_components/bootstrap/dist/css/
    - bower_components/underscore/
    - bower_components/backbone/
    - bower_components/layoutmanager/
    - bower_components/tabletop/src/
    - bower_components/isotope/dist/
  js_compressor: yui
  css_compressor: yui
  cache: true
